# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4248db06cd0ddaa64f1f9b1b6cb1d4cba5fc04287b640f76649f14507874e76f79b4e34c666c4225bc9c917fc639fa1e5138d2b6189aa2eba117759c9a44f0df

test:
  secret_key_base: 2c66429b2b4d823a6f0e32e420dd0897d49dfa530d2a96c012aef7ecccd86f583d8ce87686c738000de1339e7e3f2fb201b65c580f453520e796eb07b99cd300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
